# Generated by Django 4.2 on 2024-01-11 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(help_text='yyyy-mm-dd')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ready_to_donate', models.BooleanField(default=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.bloodgroup')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.district')),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('donation_location', models.CharField(max_length=100)),
                ('date_of_donation', models.DateField(help_text='yyyy-mm-dd')),
                ('pin_code', models.IntegerField(help_text='Pin code for editing request later', unique=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.bloodgroup')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.district')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_user', models.CharField(max_length=30)),
                ('first_user', models.CharField(max_length=30)),
                ('last_user', models.CharField(max_length=30)),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('patient_blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.bloodgroup')),
            ],
        ),
    ]
