# Generated by Django 4.2 on 2024-01-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_final', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
    ]
