# Generated by Django 4.2 on 2024-01-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_final', '0002_rename_patient_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patient_user',
        ),
    ]
