# Generated by Django 4.2.7 on 2024-01-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_final', '0003_remove_patients_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_user',
            field=models.CharField(default='user', max_length=30, null=True),
        ),
    ]
