# Generated by Django 4.2.7 on 2024-01-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_final', '0004_patients_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_user',
            field=models.CharField(max_length=30),
        ),
    ]
