# Generated by Django 4.2 on 2024-01-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_final', '0006_alter_patients_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patient_user',
        ),
    ]
