# Generated by Django 4.2 on 2024-01-12 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_final', '0007_remove_patients_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='last_user',
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_blood', models.CharField(max_length=5)),
                ('patient_gender', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
