# Generated by Django 4.2 on 2024-01-12 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_final', '0008_remove_patients_first_user_remove_patients_last_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(help_text='yyyy-mm-dd')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('need_donation', models.BooleanField(default=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.bloodgroup')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_final.district')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='patient_blood',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
