# Generated by Django 4.2 on 2024-01-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_final', '0010_alter_userextend2_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend2',
            name='patient',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
